"""ajout date sortie complete sur oeuvre

Revision ID: 17f56cef4358
Revises: 6f77cd47f432
Create Date: 2026-08-22 15:34:33.477910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f56cef4358'
down_revision: Union[str, None] = '6f77cd47f432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('date_sortie', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oeuvre', 'date_sortie')
    # ### end Alembic commands ###
