"""remplace note_allocine et note_sens_critique par note_tmdb

Revision ID: 59b85e90c97d
Revises: ead1059f36d2
Create Date: 2026-07-30 12:18:47.328817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b85e90c97d'
down_revision: Union[str, None] = 'ead1059f36d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('note_tmdb', sa.Float(), nullable=True))
    op.drop_column('oeuvre', 'note_sens_critique')
    op.drop_column('oeuvre', 'note_allocine')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('note_allocine', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('oeuvre', sa.Column('note_sens_critique', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('oeuvre', 'note_tmdb')
    # ### end Alembic commands ###
