"""ajoute nb salles predites sur oeuvre

Revision ID: 67402bda6380
Revises: ec95ddd26155
Create Date: 2026-08-26 14:26:10.248060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67402bda6380'
down_revision: Union[str, None] = 'ec95ddd26155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('nb_salles_predites', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oeuvre', 'nb_salles_predites')
    # ### end Alembic commands ###
