"""ajoute id_allocine sur oeuvre

Revision ID: 67fe0c10e8a8
Revises: 17f56cef4358
Create Date: 2026-08-22 19:49:04.220623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fe0c10e8a8'
down_revision: Union[str, None] = '17f56cef4358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('id_allocine', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'oeuvre', ['id_allocine'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oeuvre', type_='unique')
    op.drop_column('oeuvre', 'id_allocine')
    # ### end Alembic commands ###
