"""ajoute langue originale sur oeuvre

Revision ID: 74c7994fd9a7
Revises: 67fe0c10e8a8
Create Date: 2026-08-26 09:27:44.347653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c7994fd9a7'
down_revision: Union[str, None] = '67fe0c10e8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('langue_originale', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oeuvre', 'langue_originale')
    # ### end Alembic commands ###
