"""id_tmdb non unique pour permettre les reprises

Revision ID: aa4ce62b4ff7
Revises: 752affd1662e
Create Date: 2026-07-31 10:23:12.383282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4ce62b4ff7'
down_revision: Union[str, None] = '752affd1662e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oeuvre_id_tmdb_key'), 'oeuvre', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('oeuvre_id_tmdb_key'), 'oeuvre', ['id_tmdb'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
