"""ajout note_imdb sur oeuvre

Revision ID: c43b5ec14753
Revises: 59b85e90c97d
Create Date: 2026-07-30 13:47:03.791449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43b5ec14753'
down_revision: Union[str, None] = '59b85e90c97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('note_imdb', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oeuvre', 'note_imdb')
    # ### end Alembic commands ###
