"""ajout id_jpbox id_tmdb sur oeuvre

Revision ID: ead1059f36d2
Revises: f395c781e413
Create Date: 2026-07-30 10:49:01.983650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead1059f36d2'
down_revision: Union[str, None] = 'f395c781e413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('id_jpbox', sa.Integer(), nullable=True))
    op.add_column('oeuvre', sa.Column('id_tmdb', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'oeuvre', ['id_tmdb'])
    op.create_unique_constraint(None, 'oeuvre', ['id_jpbox'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oeuvre', type_='unique')
    op.drop_constraint(None, 'oeuvre', type_='unique')
    op.drop_column('oeuvre', 'id_tmdb')
    op.drop_column('oeuvre', 'id_jpbox')
    # ### end Alembic commands ###
