"""ajoute budget et nb salles semaine 1 sur oeuvre

Revision ID: ec95ddd26155
Revises: 74c7994fd9a7
Create Date: 2026-08-26 13:57:56.693770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec95ddd26155'
down_revision: Union[str, None] = '74c7994fd9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oeuvre', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('oeuvre', sa.Column('nb_salles_semaine1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oeuvre', 'nb_salles_semaine1')
    op.drop_column('oeuvre', 'budget')
    # ### end Alembic commands ###
