"""schema initial

Revision ID: f395c781e413
Revises: 
Create Date: 2026-07-29 16:06:19.077278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f395c781e413'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('id_acteur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_de_naissance', sa.Date(), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_acteur')
    )
    op.create_table('compte',
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CINEMA', 'ADMIN', name='rolecompte'), nullable=False),
    sa.Column('nom_cinema', sa.String(length=255), nullable=True),
    sa.Column('date_inscription', sa.Date(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('statut_compte', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_compte'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('genre',
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.Column('nom_genre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_genre')
    )
    op.create_table('nature',
    sa.Column('id_nature', sa.Integer(), nullable=False),
    sa.Column('nom_nature', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_nature')
    )
    op.create_table('production',
    sa.Column('id_production', sa.Integer(), nullable=False),
    sa.Column('nom_societe', sa.String(length=255), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('date_fondation', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_production')
    )
    op.create_table('realisateur',
    sa.Column('id_realisateur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_de_naissance', sa.Date(), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_realisateur')
    )
    op.create_table('oeuvre',
    sa.Column('id_oeuvre', sa.Integer(), nullable=False),
    sa.Column('nom_francais', sa.String(length=255), nullable=False),
    sa.Column('nom_original', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('annee_sortie', sa.Integer(), nullable=True),
    sa.Column('note_allocine', sa.Float(), nullable=True),
    sa.Column('note_sens_critique', sa.Float(), nullable=True),
    sa.Column('mot_cle_1', sa.String(length=50), nullable=True),
    sa.Column('mot_cle_2', sa.String(length=50), nullable=True),
    sa.Column('mot_cle_3', sa.String(length=50), nullable=True),
    sa.Column('entrees_premiere_semaine', sa.Integer(), nullable=True),
    sa.Column('id_nature', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_nature'], ['nature.id_nature'], ),
    sa.PrimaryKeyConstraint('id_oeuvre')
    )
    op.create_table('acteur_oeuvre',
    sa.Column('id_acteur', sa.Integer(), nullable=False),
    sa.Column('id_oeuvre', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_acteur'], ['acteur.id_acteur'], ),
    sa.ForeignKeyConstraint(['id_oeuvre'], ['oeuvre.id_oeuvre'], ),
    sa.PrimaryKeyConstraint('id_acteur', 'id_oeuvre')
    )
    op.create_table('genre_oeuvre',
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.Column('id_oeuvre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id_genre'], ),
    sa.ForeignKeyConstraint(['id_oeuvre'], ['oeuvre.id_oeuvre'], ),
    sa.PrimaryKeyConstraint('id_genre', 'id_oeuvre')
    )
    op.create_table('production_oeuvre',
    sa.Column('id_production', sa.Integer(), nullable=False),
    sa.Column('id_oeuvre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_oeuvre'], ['oeuvre.id_oeuvre'], ),
    sa.ForeignKeyConstraint(['id_production'], ['production.id_production'], ),
    sa.PrimaryKeyConstraint('id_production', 'id_oeuvre')
    )
    op.create_table('realisateur_oeuvre',
    sa.Column('id_realisateur', sa.Integer(), nullable=False),
    sa.Column('id_oeuvre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_oeuvre'], ['oeuvre.id_oeuvre'], ),
    sa.ForeignKeyConstraint(['id_realisateur'], ['realisateur.id_realisateur'], ),
    sa.PrimaryKeyConstraint('id_realisateur', 'id_oeuvre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realisateur_oeuvre')
    op.drop_table('production_oeuvre')
    op.drop_table('genre_oeuvre')
    op.drop_table('acteur_oeuvre')
    op.drop_table('oeuvre')
    op.drop_table('realisateur')
    op.drop_table('production')
    op.drop_table('nature')
    op.drop_table('genre')
    op.drop_table('compte')
    op.drop_table('acteur')
    # ### end Alembic commands ###
